version: '2'

services:
   travislint:
      image: drunner/travislint
      volumes:
         - "${TRAVISDIR}:/pwd"
      command: travis lint --skip-completion-check /pwd/.travis.yml
      network_mode: "bridge"
